# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://www.puremoe.net/"

languageCode = "en-us"
title = "technical notes"
theme = "hugo-theme-one"
googleAnalytics = "UA-123-45"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]

