---
title: visualizing syntactic dependencies
author: ''
date: '2020-01-25'
slug: visualizing-syntactic-dependencies
categories: []
tags: []
---

Dependency parsing via `udpipe` and visualization of dependencies via `igraph` and `ggraph`.  Graph function (below) taken directly from [this post](http://bnosac.be/index.php/blog/93-dependency-parsing-with-udpipe/).  The author, [J. Wiffels](https://github.com/jwijffels), is an incredible NLP resource.


## Create annotation object

```{r include=FALSE}
## Location of udpipe annotator model
local_annotator <- '/home/jtimm/jt_work/work01/plants_entities_clintrials/resources/'
```


```{r message=FALSE, warning=FALSE}
setwd(local_annotator)
udmodel <- udpipe::udpipe_load_model('english-ewt-ud-2.3-181115.udpipe')
sentence <- "I wish for him only good things"
sent_depend <- udpipe::udpipe(sentence , udmodel$file)
```


## Dependency visualization function

```{r message=FALSE, warning=FALSE}
library(tidyverse)
plot_annotation <- function(x, size = 3){
  
  x <- x[!is.na(x$head_token_id), ]
  x <- x[x$sentence_id %in% min(x$sentence_id), ]
  edges <- x[x$head_token_id != 0, c("token_id", 
                                     "head_token_id", 
                                     "dep_rel")]
  edges$label <- edges$dep_rel
  
  g <- igraph::graph_from_data_frame(edges,
                                     vertices = x[, c("token_id",
                                                      "token",
                                                      "lemma",
                                                      "upos",
                                                      "xpos",
                                                      "feats")],
                                     directed = TRUE)
  
  ggraph::ggraph(g, layout = "linear") +
    ggraph::geom_edge_arc(ggplot2::aes(label = dep_rel, vjust = -0.20),
                          arrow = grid::arrow(length = unit(4, 'mm'), 
                                              ends = "last", 
                                              type = "closed"),
                          end_cap = ggraph::label_rect("w123"),
                          label_colour = "#55752f", 
                          check_overlap = TRUE, 
                          label_size = size) +
    
    ggraph::geom_node_label(ggplot2::aes(label = token), 
                            col = "steelblue", 
                            size = size, 
                            fontface = "bold") +
    
    ggraph::geom_node_text(ggplot2::aes(label = upos), 
                           nudge_y = -0.35, 
                           size = size) +
    
    ggraph::theme_graph() 
  }
```





## Apply function

```{r fig.height=5, message=FALSE, warning=FALSE}
plot_annotation(sent_depend, size = 4) +
  labs(title = sentence)
```
