---
title: class II senators
author: ''
date: '2020-01-20'
slug: class-II-senators
---


A quick investigation/roll call of Class II Senators (n = 33) up for re-election in November.  *Plus special elections for two Class III seats*.  Via the `uspoliticalextras` R package.


```{r message=FALSE, warning=FALSE}
library(tidyverse)
sens <- uspoliticalextras::uspol_csusa_senate_bios %>%
  mutate(class = ifelse(last_name %in% c('McSally', 'Isakson'), 
                        'II', class)) %>%
  filter(congress == 116)

sens %>%  
  filter(class == 'II') %>%
  group_by(party) %>%
  count() %>%
  knitr::kable()
```

---


```{r}
sens <- sens %>%
  #filter(class == 'II')    %>%
  mutate(sen = paste0(last_name, '-', 
                      #toupper(substr(party, 1, 1)), 
                      #'-', 
                      state_abbrev))

sens %>% filter(party == 'democrat' & class == 'II') %>% 
  summarize(DEMOCRATS = paste0(sen, collapse = ' | ')) %>%
  knitr::kable()
```
 

```{r}
sens %>% filter(party == 'republican' & class == 'II') %>% 
  summarize(REPUBLICANS = paste0(sen, collapse = ' | ')) %>%
  knitr::kable()
```





## By party affiliation & state

```{r fig.height=6, message=FALSE, warning=FALSE}
library(sf)
pal <- c('#395f81', 'gray', '#9e5055')
names(pal) <- c('II-Dem', 'I/III', 'II-Rep')

maps <- uspoliticalextras::uspol_dkos_equalarea_sf$tile_outer %>% 
  left_join(sens %>% 
              mutate(class1 = case_when(class == 'II' & party == 'democrat' ~ 'II-Dem',
                                        class == 'II' & party == 'republican' ~ 'II-Rep',
                                        class != 'II' ~ 'I/III')))  

maps %>%  
  ggplot() + 
  geom_sf(aes(fill = class1),
          color = 'black', 
          alpha = .85) + 
  ggsflabel::geom_sf_text(data = uspoliticalextras::uspol_dkos_equalarea_sf$tile_inner,
                          aes(label = state_abbrev), 
                          size = 3,
                          color = 'white') +
  scale_fill_manual(values = pal) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        legend.title=element_blank(),
        legend.position = 'bottom') +
  labs(title = "States by Party Affiliation")
```



## 2016 Trump margins

### Shaky Democrats

```{r}
margs <- uspoliticalextras::uspol_medsl_returns_pres_state %>%
  filter(year == 2016) %>%
  inner_join(sf::st_drop_geometry(maps) %>%
               select(state, first_name, last_name, class, party) %>% 
               filter(class == 'II'), by = 'state') %>%
  mutate(trump_margins = round(republican -democrat, 1),
         name = paste0(last_name, ', ', first_name)) %>%
  select(state_po, name, party.y, trump_margins) 

margs %>%
  filter(party.y == 'democrat' & trump_margins > -10) %>%
  knitr::kable()
```


### Shaky Republicans

```{r}
margs %>%
  filter(party.y == 'republican' & trump_margins < 10) %>%
  knitr::kable()
```


### Safe/less shaky seats

```{r}
margs %>%
  filter(!(party.y == 'republican' & trump_margins < 10) &
           !(party.y == 'democrat' & trump_margins > -10) ) %>%
  knitr::kable() %>%
  kableExtra::kable_styling(full_width = T)
```


